spring:
  application:
    name: graphql-api-service

clients:
  order:
    base-url: ${ORDER_BASE:http://localhost:8081}
  inventory:
    base-url: ${INVENTORY_BASE:http://localhost:8082}

server:
  port: ${PORT:8085}